### PR TITLE
Maintenance and doc updates

### PR DESCRIPTION
**Pull request by ablaom**
This PR, addresses #15 .

For this PR to work, an administrator needs to:

- [ ] Setup ssh keys for Documenter; [instructions](https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#travis-ssh)
- [ ] Setup ssh keys for CompatHelper; [instructions](https://juliaregistries.github.io/CompatHelper.jl/dev/#Creating-SSH-Key)

What this PR does:

- moves CI from .travis (which now has limited free support) to a GH action
- adds TagBot for new releases
- add CompatHelper to automatically generate compatibility updates PR's
- updates the Documenter-generated documentation: The current`jldoctest` blocks (which aren't currently enabled or correct) are each replaced with an `@example` blocks or a plain `julia` block as appropriate. The two `@example` blocks allow us to drop two images of dataframe output, as they are now automatically generated. These two blocks include the the MLJ related-code. So, in the future, if these fail, this will be manifest in the doc generation log (but unfortunately the GH-action will still silently pass). The MLJ code has been updated to work with the latest version of MLJ 0.17. In the parallel example, instead of `addprocs(6)` I've put `addprocs(exeflags="--project=$(Base.active_project())")` which adds all available workers and ensures the master package environment is inherited by the new workers (the `@example` block fails otherwise). Also, the user will want to do this (or something equivalent) or face the same problem.
- updates the CI badge in the readme
- removes the "Examples" section from the readme, as this duplicates the examples in the Documenter documentation.

### CODE REVIEW

**Comment by nredell** [comment]
This is a great update. Sending it off to the Julia package manager soon. Thanks

**Comment by ablaom** [comment]
Thanks. Assuming you have setup those keys, you may need to create a dummy PR to trigger doc generation. It looks like the gh-pages docs are not yet updated.

**Comment by ablaom** [comment]
@nredell Could you please set up those keys (see check list at the top) and create a dummy PR to deploy the new documentation? Then we could close #15 (and I can close https://github.com/alan-turing-institute/MLJ.jl/issues/864).

**Comment by nredell** [comment]
I'm ready to transfer ownership of this repo. Let's make that happen.

**Comment by ablaom** [comment]
Okay. I'm assuming you mean transfer to [JuliaAI](https://github.com/JuliaAI)?

I've sent you an invitation for membership at JuliaAI. This should allow you to transfer ownership. This is pretty easy - just go down to the bottom of your Settings page and follow your nose.

**Pull request merged**
